app_pass: abc
bot_pass: abc
bro_announce_id: '5'
bro_general_id: '4'
bro_role_select_id: '6'
bro_wait_id: '3'
email: abc@gmail.com
msa: NJIT
server_id: '1'
sis_announce_id: '9'
sis_general_id: '8'
sis_role_select_id: '10'
sis_wait_id: '7'
verify_id: '2'
